#version 450

#include "define.glsl"
#include "grid_utils.glsl"
#include "particle_utils.glsl"

layout(std140, binding = 0) buffer ParticleSSBO
{
  Particle particles[];
};

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

/*
  Fill cellID value for each particle to prepare radix sort.
*/
void main()
{
  uint index = gl_GlobalInvocationID.x;

  const vec3 pos = particles[index].position;

  particles[index].cellID = getCell1DIndexFromPos(pos);
}