// Preprocessor defines following constant variables in Boids.cpp
// ABS_WALL_X            - absolute position of the walls in x,y,z
// GRID_RES_X                - resolution of the grid
// GRID_CELL_SIZE_XYZ          - size of a cell, size / res of grid
// GRID_NUM_CELLS          - total number of cells in the grid
// NUM_MAX_PARTS_IN_CELL   - maximum number of particles taking into account in a single cell in simplified mode

// Most defines are in define.cl
// define.cl must be included as first file.cl to create OpenCL program

// one desc set layout
// uint pCellID
// float4 pPos
// uint2 cStartEndPartID

// bind once
// dispatch the diff pipelines and their entry points

/*
  Reset cellID buffer. For radix sort purpose.
*/
__kernel void resetCellIDs(__global uint* pCellID)
{
  // For all particles, giving cell ID above any available one
  // the ones not filled later (i.e not processed because index > nbParticles displayed)
  // will be sorted at the end and not considered after sorting
  pCellID[ID] = GRID_NUM_CELLS * 2 + ID;
}

/*
  Fill cellID buffer. For radix sort purpose.
*/
__kernel void fillCellIDs( //Input
    const __global float4* pPos,
    //Output
    __global uint* pCellID)
{
  const float4 pos = pPos[ID];

  const uint cell1DIndex = getCell1DIndexFromPos(pos);

  pCellID[ID] = cell1DIndex;
}

/*
  Reset startEndPartID buffer for each cell.
*/
__kernel void resetStartEndCell(__global uint2* cStartEndPartID)
{
  // Resetting with 1 as starting index and 0 as ending index
  // Little hack to bypass empty cell further
  cStartEndPartID[ID] = (uint2)(1, 0);
}

/*
  Find first partID for each cell.
*/
__kernel void fillStartCell( //Input
    const __global uint* pCellID,
    //Output
    __global uint2* cStartEndPartID)
{
  const uint currentCellID = pCellID[ID];

  if (ID > 0 && currentCellID < GRID_NUM_CELLS)
  {
    uint leftCellID = pCellID[ID - 1];
    if (currentCellID != leftCellID)
    {
      // Found start
      cStartEndPartID[currentCellID].x = ID;
    }
  }
}

/*
  Find last partID for each cell.
*/
__kernel void fillEndCell( //Input
    const __global uint* pCellID,
    //Output
    __global uint2* cStartEndPartID)
{
  const uint currentCellID = pCellID[ID];

  if (ID != get_global_size(0) && currentCellID < GRID_NUM_CELLS)
  {
    const uint rightCellID = pCellID[ID + 1];
    if (currentCellID != rightCellID)
    {
      // Found end
      cStartEndPartID[currentCellID].y = ID;
    }
  }
}

/* 
  Adjust last partID for each cell, capping it with max number of parts in cell in simplified mode.
*/
__kernel void adjustEndCell(__global uint2* cStartEndPartID)
{
  const uint2 startEnd = cStartEndPartID[ID];

  if (startEnd.y > startEnd.x)
  {
    const uint newEnd = startEnd.x + min(startEnd.y - startEnd.x, (uint)NUM_MAX_PARTS_IN_CELL);
    cStartEndPartID[ID] = (uint2)(startEnd.x, newEnd);
  }
}
