#version 450

#include "define.glsl"
#include "grid_utils.glsl"
#include "particle_utils.glsl"

layout(std140, binding = 0) buffer ParticleSSBO
{
  Particle particles[];
};

layout(std430, binding = 1) buffer StartEndPartIdSSBO
{
  uvec2 cStartEndPartIds[];
};

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
  uint index = gl_GlobalInvocationID.x;

  cStartEndPartIds[index] = uvec2(0, 0);
}